---
- import_tasks: ssh-server.yml
- name: download chrome-remote-desktop deb
  ansible.builtin.get_url:
    # CRD 125 seems not working https://askubuntu.com/questions/1512423/chrome-remote-desktop-in-24-04
    url: https://deb.rug.nl/ppa/mirror/dl.google.com/linux/chrome-remote-desktop/deb/pool/main/c/chrome-remote-desktop/chrome-remote-desktop_124.0.6367.18_amd64.deb
    dest: /tmp/chrome-remote-desktop.deb

- name: Install chrome-remote-desktop deb package
  become: yes
  ansible.builtin.apt:
    deb: /tmp/chrome-remote-desktop.deb
